### PR TITLE
Refresh coordinator in consumer group

### PR DESCRIPTION
**Pull request by muirrn**
Now if the consumer group gets ErrNotCoordinatorForConsumer when
starting to consume it will refresh the coordinator instead of trying
to use the wrong/stale coordinator forever.

### CODE REVIEW

**Comment by varun06** [comment]
Looks good. But consumer group functionality has very few tests :(

**Comment by muirrn** [comment]
Yes, I think we need tests that run against a multi-node cluster so we can test all the interesting things that happen when you restart nodes. I would be happy to add coverage to that type of test suite, but I'm not prepared to set all that up right now.

**Comment by bai** [comment]
I could help with multi-node cluster infra via docker-compose on Monday.

**Comment by varun06** [comment]
@bai I am trying to setup one locally on my mac, man it is hard on mac, specially SR and REST-PROXY part.

**Comment by varun06** [comment]
@bai I am using same, but their cluster ones don't have Schema registry and rest proxy.

**Comment by bai** [comment]
Oh well ¯\_(ツ)_/¯ I'll spare some time on Monday to unblock this.

**Comment by varun06** [comment]
I am making some advances, if I can get it going today, I will send `docker-compose.yml` your way.

**Comment by varun06** [comment]
@bai https://gist.github.com/varun06/7346ed726a1531022a85fd162af4e402

This is a working copy on my local mac machine. I had some trouble making multi zk works, so I only have 1 zk and 3 kafka brokers with SR and Kafka-rest. hope it will be helpful.

**Comment by varun06** [comment]
@muirrn What's the status on this?

**Comment by muirrn** [comment]
If I remember, I was waiting for a multi-node test suite to be in place so I could add my test coverage. Are there tests now that use your docker compose setup?

**Comment by varun06** [comment]
I believe not, @bai what do we need to do for a multi node setup?

**Comment by dnwe** [comment]
@muirrn happened to see this old PR and I think the fix from this PR was eventually covered by a change in PR https://github.com/Shopify/sarama/pull/1231 so this one can probably be closed now

**Comment by muirrn** [comment]
@dnwe Thanks. It does seem to address the same issue, although hard to be sure of anything without multinode tests.

**Comment by dnwe** [comment]
What do you mean by multi node tests? Afaik the vagrant cluster that is spun up for Travis is a 3 broker kafka cluster?

**Comment by muirrn** [comment]
> Afaik the vagrant cluster that is spun up for Travis is a 3 broker kafka cluster

Oh, if there are tests that exercise multi-node cluster behavior then that is great. I assumed there wasn't any based on this PR still being in limbo.

**Pull request closed without merging**
