### PR TITLE
Correctly handle unencodable messages in the producer

### PR DESCRIPTION
**Pull request by eapache**
Quick fix for #449, pending more thought and writing tests etc.

### CODE REVIEW

**Comment by cep21** [comment]
What if the flag setting happened inside return error or return success?

**Comment by wvanbergen** [comment]
can we simply set the returned flag in the `return` functions themselves?

**Comment by eapache** [comment]
> What if the flag setting happened inside return error or return success?

I suspect I'll end up getting rid of the flag (and the setting of the array to `nil` which it partially replaced) entirely, as that seems very fragile. Yes, setting the flag in the returning functions would have fixed this issue, but it also would have potentially hidden others since there are a lot of other places we could use messages without checking for the flag.

I just threw this up as-is for @cep21's benefit, I won't merge it yet.

**Comment by eapache** [comment]
Ya, setting the flag isn't ideal at all because it results in messages reaching the user with flags set, which breaks our API guarantee.

**Comment by eapache** [comment]
I've just pushed a better (i.e. actually correct) fix to this branch. It's still not ideal architecturally, but I think I'm happy enough with it to release it as v1.5.1 if you both agree.

**Comment by cep21** [comment]
This code works for me.  There's something stinky about the existence of ```keyCache, valueCache```, but I think that's what you're talking about w/ "not ideal" and it is an improvement for sure.  I'll probably merge it into my SafeWaitGroup branch.

**Comment by eapache** [comment]
> but I think that's what you're talking about w/ "not ideal"

Understatement is a bad habit of mine :P

**Comment by wvanbergen** [comment]
:+1: - this fix looks pretty straightforward to me.

Side note: another good reason to remove the Encoder interface for sarama v2. :)

**Comment by eapache** [comment]
> Side note: another good reason to remove the Encoder interface for sarama v2. :)

Yup :)

**Comment by eapache** [comment]
I'll release 1.5.1 with this shortly and then file another ticket to refactor/solve it properly.

**Comment by eapache** [comment]
1.*6*.1 released.

**Comment by eapache** [comment]
The longer-term refactor has been rolled into #433 which has just suddenly gone from "nice to have eventually" to "reasonably important".

**Pull request merged**
