### PR TITLE
Add an example of using the consumer

### LINKED ISSUE #556: Option: Provide an example of consuming message
In the example chapter of the document,  I can't find an example of consuming message.
And in the test case, there doesn't has an complete example too.

### PR DESCRIPTION
**Pull request by eapache**
Somehow we never added this.

@wvanbergen @i19 

Fixes #556.

### CODE REVIEW

**Comment by wvanbergen** [comment]
:+1:, this is a good start. (I could have sworn we already had something like this, but apparently not).

Might be nice to also have a more complete example that consumes all partitions of a topic. Maybe that is better suited for the examples folder though.

**Comment by i19** [comment]
Thx a lot. 
I found that sarama doesn't have connection to ZooKeeper. So I wonder how you guys perform the rebalance and how to scale the consumer?

**Comment by eapache** [comment]
Zookeeper logic is in a separate package: https://github.com/wvanbergen/kafka

**Comment by i19** [comment]
Cool ! Thx again !

**Pull request merged**
