### PR TITLE
Fix consuming compacted topic

### PR DESCRIPTION
**Pull request by gburanov**
See https://github.com/Shopify/sarama/pull/1086#issuecomment-442226755 for details

### CODE REVIEW

**Comment by varun06** [comment]
Does the test in linked PR cover this case too?

**Comment by gburanov** [comment]
@varun06 no, I will add the test if the community think this pr make sense

**Comment by annymsMthd** [comment]
What's the status of this PR? It fixes an issue we are currently having with sarama and goka

**Comment by varun06** [comment]
If that's the case, let's get this PR passing and then we can ask it to be merged.

**Comment by gburanov** [comment]
Ok, I will try to get CI working =) PS: We used this fix in our fork since November, and it works great

**Comment by varun06** [comment]
Nice, let's get CI working and then we can merge it.

**Comment by annymsMthd** [comment]
Are we just at a stalemate here or something?

**Comment by gburanov** [comment]
I am fine if somebody will just merge this pr for me - I do not want to sign CLA for this. CI is green expect CLA

**Comment by varun06** [comment]
@bai What do you think?

**Comment by bai** [comment]
Thanks for contributing!

**Pull request merged**
