### PR TITLE
fix: remove use of testing.T.FailNow() inside goroutine

### PR DESCRIPTION
**Pull request by alrs**
This fixes `TestClientAutoRefreshShutdownRace()` to not fire `t.Fatal()` inside a goroutine.

`t.Fatal()` is a convenience function that calls `t.Log()` and `t.FailNow()`. `t.FailNow()` should not be called from inside a goroutine. From the godoc:

 > FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test.

This replaces the `done` channel with an `error` channel, and tests the error variable outside the goroutine.

### CODE REVIEW

**Comment by alrs** [comment]
I'm happy to fill out a CLA, should someone provide a link to one.

**Comment by bai** [comment]
Here we go, it's actually one of the failing checks: https://github.com/Shopify/sarama/pull/1601/checks?check_run_id=428029640 👀

**Comment by alrs** [comment]
@bai CLA is complete.

**Comment by bai** [comment]
Thanks for contributing.

**Pull request merged**
