### PR TITLE
KIP-546 Client quota APIs

### PR DESCRIPTION
**Pull request by agriffaut**
This PR implements the new ClientQuota API, available since Kafka 2.6.0.0

KIP: https://cwiki.apache.org/confluence/display/KAFKA/KIP-546%3A+Add+Client+Quota+APIs+to+the+Admin+Client

Protocols:
https://kafka.apache.org/protocol#The_Messages_DescribeClientQuotas
https://kafka.apache.org/protocol#The_Messages_AlterClientQuotas

### CODE REVIEW

**Comment by dnwe** [comment]
@agriffaut thanks for your contribution, this is great!

One question I had after an initial scan over the PR, was there a design goal around consistently using slices of pointers in the protocol definitions here? The slices will always either be empty or filled and will never have `nil` values, so I'm not sure why we wouldn't make these slices of the concrete type? As we (currently) have a strong coupling between the parameters for the high level functions in `admin.go` and the protocol structs, we similarly end up with `map[string]*string` etc.

**Comment by dnwe** [comment]
I rebased and it also looks like `TestDescribeClientQuotasResponse` might be flakey. Please could you take a look?
```
2021-05-05T22:41:43.7835979Z === RUN   TestDescribeClientQuotasResponse
2021-05-05T22:41:43.7836889Z     request_test.go:96: Encoding Multi Value failed
2021-05-05T22:41:43.7837592Z         got  [0 0 0 0 0 0 255 255 0 0 0 1 0 0 0 1 0 4 117 115 101 114 255 255 0 0 0 2 0 18 99 111 110 115 117 109 101 114 95 98 121 116 101 95 114 97 116 101 65 46 132 128 0 0 0 0 0 18 112 114 111 100 117 99 101 114 95 98 121 116 101 95 114 97 116 101 65 46 132 128 0 0 0 0] 
2021-05-05T22:41:43.7838308Z         want [0 0 0 0 0 0 255 255 0 0 0 1 0 0 0 1 0 4 117 115 101 114 255 255 0 0 0 2 0 18 112 114 111 100 117 99 101 114 95 98 121 116 101 95 114 97 116 101 65 46 132 128 0 0 0 0 0 18 99 111 110 115 117 109 101 114 95 98 121 116 101 95 114 97 116 101 65 46 132 128 0 0 0 0]
2021-05-05T22:41:43.7839480Z --- FAIL: TestDescribeClientQuotasResponse (0.00s)
```

**Comment by agriffaut** [comment]
@dnwe I finally managed to work again on that PR, sorry for the delay.
As you said, some pointers were useless and have been removed !

Please tell me if this looks good to you!

**Review by bai — APPROVED** [review]
LGTM

**Comment by bai** [comment]
Thanks for your contribution @agriffaut. 

I'll wait for `dnwe` to review before we ship this 🙏🏼

**Review by dnwe — APPROVED** [review]
LGTM. Thanks again for the PR and the updates 🙇

**Pull request merged**
