### PR TITLE
Add support for Kafka 0.11 Record and RecordBatch

### PR DESCRIPTION
**Pull request by wladh**
The new records format (including headers) is supported, however there's
no support for transactions or idempotent messages.
This is the first step towards issue #901

### CODE REVIEW

**Comment by eapache** [comment]
Thanks so much for this contribution, it looks pretty good. Unfortunately it's an enormous PR (1600 lines!) and I'm having trouble untangling the pieces to review it properly.

Could you split it up and submit it in a couple of smaller PRs please? Off the top of my head there are at least the following chunks that are separable:
- varint support in the encoder layer
- Castagnoli support for CRCs
- implementation of the new record and recordbatch structs at the protocol layer
- support for record/recordbatch in the producer
- support for record/recordbatch in the consumer

Don't be afraid to split it up even further though if you find good divisions. The time it takes me to review something is usually about quadratic on the number of lines of code, so the smaller the better (within reason).

**Comment by wladh** [comment]
Sure, I prefer small commits myself.

**Comment by wladh** [comment]
Do you want multiple PRs or is multiple commits in a single PR fine?

**Comment by eapache** [comment]
Multiple PRs would be preferable, but I can deal with either

**Pull request closed without merging**
