### PR TITLE
Remove broker(s) which no longer exist in metadata

### PR DESCRIPTION
**Pull request by Stephan14**
This pull request solves the problem: #1629. I find it only have update and add broker when update brokers by latest metadata, however there is no code of remove broker which if offline

### CODE REVIEW

**Comment by Stephan14** [comment]
Hey @d1egoaz, I have found some error as follows:
image
 And run test on my Mac, it show as follows:
image
I think `Got err: kafka: client has run out of available brokers to talk to` is only one log and the code is right, so I delete this log

**Comment by Stephan14** [comment]
Hey @bai @d1egoaz,   I find other PR appear some error on CI, for example https://github.com/Shopify/sarama/pull/1640/checks?check_run_id=504088005,  but it check successful. So how to solve the problem.

**Comment by d1egoaz** [comment]
Thanks @Stephan14 for the new PR, so it seems the changes that you are introducing are indeed changing/breaking some expectation in some tests. We'll need to 👀 what's going on.

**Comment by Stephan14** [comment]
Hey @d1egoaz , how about this problem is going? Can I merge this PR to master? The failures is as follow:
image

**Comment by Stephan14** [comment]
@dnwe , oh, sorry. I have fixed the problem and run `go test` on my mac successfully as follows:
image
But it runs failed in some CI as follows:
image
How to fix it

**Comment by dnwe** [comment]
@Stephan14 thanks for the fix. Looks like go actions had some issue fetching dependencies, but all the re-runs are green. Merging

**Comment by brenley** [comment]
Hello! Just curious if this will be in the next release and when this is slated for? We have observed this issue and are deciding on whether to wait or deviate from release pattern and just pull in master.

**Comment by dnwe** [comment]
@brenley theres a few other open issues and it would be good to get some testing done against the final GA of kafka 2.5 but I'd imagine we'd be able to release a semver bump within a short period of time

**Pull request merged**
