### PR TITLE
Bump confluentPlatformVersion from 6.1.1 to 6.2.0

### PR DESCRIPTION
**Pull request by null-sleep**
Part of the effort to upgrade to Kafka 2.8.0

### CODE REVIEW

**Review by vvuibert — APPROVED** [review]

**Comment by dnwe** [comment]
@null-sleep / @vvuibert are you still working on this? I notice that the functional tests failed because it seems a kafka server side error has seemingly changed, causing the assert to fail:

2021-08-09T12:18:52.0161673Z     functional_producer_test.go:104: Expected ErrUnknownTopicOrPartition, found kafka server: The request attempted to perform an operation on an invalid topic.

**Comment by bai** [comment]
@vvuibert @null-sleep Friendly bump 🙏🏼 Do you think you'd be able to look into this test failure?

**Comment by null-sleep** [comment]
I rebased off master and the tests still fail. On running `make test_functional` locally I get this stacktrace:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[65218] Failed to execute script docker-compose
panic: failed to tear down existing env: failed to run docker-compose to stop test environment: exit status 255
```
@bai

**Comment by dnwe** [comment]
Looks like the new `TestDeleteOffsetsResponse` test is a little brittle and can periodically fail. Doesn't look to have been effected by this PR (as you'd expect) so will keep re-running the CI until it passes.

Will raise an issue to look at the brittle test.

**Comment by dnwe** [comment]
woo, we've got this passing now — will merge

**Pull request merged**
