### PR TITLE
add error codes 45-60

### PR DESCRIPTION
**Pull request by buyology**

### CODE REVIEW

**Comment by eapache** [comment]
Thanks, this looks :+1: once CI is fixed up.

**Comment by eapache** [comment]
Can you please rebase this and your other PR on master now that CI is fixed?

**Comment by buyology** [comment]
Done and done :) These errors seem related to cluster not starting up properly?

**Comment by eapache** [comment]
Ya, the process of standing up a cluster on CI to test against is unfortunately a bit flaky. Most of the time I can give it a kick and it will pass the second time.

**Comment by eapache** [comment]
Thanks!

**Pull request merged**
