### PR TITLE
Upstream has spoken on retriable errors

### PR DESCRIPTION
**Pull request by eapache**
Add InvalidMessage, and re-order the others to match their definition order.

### CODE REVIEW

**Comment by wvanbergen** [comment]
When would a retry succeed? A topic that is in process of being created?

**Comment by eapache** [comment]
For `ErrUnknownTopicOrPartition`? When you have auto-create turned on.

**Comment by wvanbergen** [comment]
No, I mean `InvalidMessage`, which IIRC gets returned when you use an invalid topic name (e.g. with a slash in it.

**Comment by eapache** [comment]
That's `InvalidTopic` - `InvalidMessage` indicates a bad CRC

**Comment by wvanbergen** [comment]
D'oh. :+1: in that case

**Pull request merged**
