### PR TITLE
Fix race in broker version check

### PR DESCRIPTION
**Pull request by eapache**
Move it until after we're sure we have a version to check against. Fixes a race
found by @kchaliki (https://github.com/Shopify/sarama/pull/678#issuecomment-226786282).

Also make the which-version-do-I-need part of the protocol interface where it
belongs.

### CODE REVIEW

**Comment by kchaliki** [comment]
@eapache thanks for the fix, I can confirm I no longer get a panic due to the nil pointer, however I still don't see a timestamp applied to my messages - does it work for you?

**Comment by eapache** [comment]
I have not been able to properly test this yet; it seems there are some broker-side settings that may need to be set in addition to just producing with the right message version?

**Comment by kchaliki** [comment]
Indeed, I will dig some more

**Comment by kchaliki** [comment]
Confirmed after running

kafka-topics.sh  --zookeeper blah --alter --topic mytopic --config message.timestamp.type=LogAppendTime

I get timestamps. I think one small issue is they are millisecond timestamps and that is not accounted for correctly when parsing the response and calling time.Unix(block.Timestamp, 0)

**Comment by kchaliki** [comment]
Something like this does the trick

timestampNsec := block.Timestamp % 1000
timestampSec := block.Timestamp / 1000
timestamp := time.Unix(timestampSec, timestampNsec)

**Pull request merged**
