### PR TITLE
Update lz4 version

### PR DESCRIPTION
**Pull request by linxGnu**
Issue:
- lz4 version `github.com/pierrec/lz4 v2.0.5+incompatible` contains serious bug related to writing and checksum. Demonstration code is at: https://gist.github.com/linxGnu/c9e0e8a6f7df0251a323af37d611cb77
- Latest version `315a67e` of `github.com/pierrec/lz4` also fixed some other bugs.

Changes:
- Version of lz4 in `go.mod` and `go.sum`

### CODE REVIEW

**Comment by varun06** [comment]
Can you please make the cl build pass?

**Comment by bai** [comment]
I already pushed a fix to master, so you just need to rebase your branch.

Root cause is this (another PR where I fix this issue): https://github.com/dataDog/zstd/pull/55 — Ubuntu 14.04 ships an ancient `ld` that's not compatible with modern `binutils`.

**Comment by bai** [comment]
Oh and while you're on it, could you please sign CLA to make sure it's all green?

**Comment by linxGnu** [comment]
I will close and reopen it soon. Many thanks for your reviews 👍

**Pull request closed without merging**
