### PR TITLE
pull request to please lint gods

### PR DESCRIPTION
**Pull request by varun06**

### CODE REVIEW

**Comment by bai** [comment]
whateverworks

**Comment by varun06** [comment]
ha, exactly. @bai are we planning to cut a release soon. we have bunch of commits?

**Comment by bai** [comment]
Yeah, I want to cut is asap. One thing that I wanted to include is support for zstd 1.3.8. Kafka 2.2.0 uses zstd 1.3.8, while we use DataDog's zstd 1.3.5.

If my zstd PR doesn't go through today, I'll compile changelog + make a release tomorrow.

**Comment by valyala** [comment]
PTAL https://github.com/valyala/gozstd , which includes support for zstd 1.3.8 .

**Comment by bai** [comment]
@valyala I bumped zstd dep in https://github.com/Shopify/sarama/pull/1350. Out of curiosity, how's your implementation different from DataDogs?

**Comment by valyala** [comment]
gozstd has [the following features](https://github.com/valyala/gozstd/blob/master/README.md#features) comparing to DataDog's zstd:

* It vendors upstream zstd without any modifications in the [zstd](https://github.com/valyala/gozstd/tree/master/zstd) folder. The update process for the upstream `zstd` is easy - just run `make update-zstd` from the root of the repository. For example, I just updated the upstream `zstd` to v1.4.0 in [this commit](https://github.com/valyala/gozstd/commit/0ed9d480be581ffab9e417288a79ea9be8ed51c1).
* It is optimized for speed. [The API](https://godoc.org/github.com/valyala/gozstd) may be easily used in zero allocations mode.
* It provides faster and more efficient stream compression. It provides proper [Writer.Flush](https://godoc.org/github.com/valyala/gozstd#Writer.Flush) call for network apps.
* It supports dictionaries.

**Comment by bai** [comment]
Thanks @valyala, will take a look!

**Pull request merged**
