### PR TITLE
Satisfy the error interface in create responses

### PR DESCRIPTION
**Pull request by dnwe**
Contributes-to: Shopify/sarama#1153

Signed-off-by: Dominic Evans <dominic.evans@uk.ibm.com>

### CODE REVIEW

**Comment by varun06** [comment]
Hey @dnwe, can you please add some tests and we can merge it then?

**Comment by dnwe** [comment]
@varun06 thanks, rebased and re-pushed with some tests added

**Comment by dnwe** [comment]
@varun06 travis build fixed after removing the test that is no longer valid

**Comment by varun06** [comment]
Thanks, I will have a look today.

**Comment by bai** [comment]
Thanks!

**Pull request merged**
