### PR TITLE
consumer group support

### PR DESCRIPTION
**Pull request by dynamix**
WIP
- add tests
- support auto and manual commit as in Java API
- more manual tests

### CODE REVIEW

**Comment by eapache** [comment]
Have you looked at https://github.com/bsm/sarama-cluster ?

**Comment by dynamix** [comment]
Ahh sorry I open the PR a bit to early (not done yet). This is based partly on the code of https://github.com/bsm/sarama-cluster. However it does use the OffsetMananger from sarama directly + test / functional test will be done sarama style. And tbh I think it would be nice to make this a part of sarama at some point in time so it is on par with the current Java consumer ;-)

**Comment by dynamix** [comment]
I will close this and reopen after it is done :-)

**Comment by eapache** [comment]
OK cool, I've been meaning to tackle this for a while now.

Take your time, I'm busy with other things right now and won't have the time to review any big PRs for the next couple of weeks anyway.

**Pull request closed without merging**
