### PR TITLE
Remove redundant switch-case, fix doc typos

### PR DESCRIPTION
**Pull request by bestgopher**
The switch-case here is redundant. There is the logic of this part of the code in the `decompress` function.

### CODE REVIEW

**Comment by bestgopher** [comment]
how to re-check CLA status?

**Review by dnwe — APPROVED** [review]
LGTM

**Comment by bai** [comment]
Thanks for contributing!

**Comment by bestgopher** [comment]
> Thanks for contributing!

how to retest ci？

**Review by dnwe — APPROVED** [review]

**Review by bai — APPROVED** [review]

**Pull request merged**
