### PR TITLE
add support for aws mks iam

### PR DESCRIPTION
**Pull request by sethpollack**
fixes https://github.com/Shopify/sarama/issues/1985

usage would look like:

```
cfg.Net.SASL.Mechanism = sarama.SASLMechanism(sarama.SASLTypeAWSMSKIAM)
cfg.Net.SASL.AWSMSKIAM = sarama.AWSMSKIAMConfig{
    Region: "us-east-1",
}

```

### CODE REVIEW

**Comment by lomluca** [comment]
I was implementing the same feature for a Kafka Terraform provider that relies on Sarama and I went for this last solution @sethpollack mentioned: using a custom `SCRAMClientGeneratorFunc`. I think passing a pluggable function is the best solution, in this way Sarama could be very flexible supporting many (potential) SASL/SCRAM-based mechanism. 

The problem is Sarama is not flexible right now: in many points the code checks if the mechanism is strictly "SASLTypeSCRAMSHA256" or "SASLTypeSCRAMSHA512", there is no room to add new mechanisms. I would propose to enforce a generalized "SASLTypeSCRAM" mechanism and, in addition to that, introduce a flexible mechanism name (i.e. "SCRAM-SHA-256, "SCRAM-SHA-512", "AWS_MSK_IAM") that could be externally specified. I think these modifications, with the already-in-place possibility to specify a custom `SCRAMClientGeneratorFunc`, allow what we want to achieve.

What do you think?

**Review by tooptoop4 — APPROVED** [review]

**Comment by michaelwagler** [comment]
Any updates on this? We use Sarama for a large number of our services, and would love to keep using it, but are considering moving over to kafka-go because it has IAM support.

**Comment by tooptoop4** [comment]
@sethpollack can u rebase the conflicts?

**Comment by tooptoop4** [comment]
hoo gonna merg dis?

**Comment by tooptoop4** [comment]
@sethpollack for SASL.User/SASL.Password do you have to provide a static accesskey/secretkey?

**Comment by bpaquet** [comment]
Please :)

**Comment by galamit1** [comment]
Any updates? Do you know when it will be merged?

**Comment by austinorth** [comment]
@sethpollack would you have a moment to sign the CLA so we can get this merged? 🙏🏻

**Comment by sethpollack** [comment]
@austinorth unfortunately that CLA is asking for way too much personal information, I don't feel comfortable signing it.

**Comment by austinorth** [comment]
@sethpollack ahhh worddd

**Comment by bpaquet** [comment]
@sethpollack can I fork you PR to get it merged?

**Comment by sethpollack** [comment]
@bpaquet Yes

**Comment by joaocc** [comment]
Hi! Is there any update on this PR? Thanks

**Pull request closed without merging**
