### PR TITLE
Add some simple producer benchmarks

### PR DESCRIPTION
**Pull request by eapache**
@Shopify/kafka

### CODE REVIEW

**Comment by wvanbergen** [comment]
Should we store historical results somewhere, e.g. on a wiki page?

**Comment by eapache** [comment]
I've played with these a bit and the results aren't terribly consistent. I'm not sure how useful they will be in practice. If somebody else wants to try running them and see if they can get reliable results that would be useful.

**Comment by wvanbergen** [comment]
:shipit:

**Comment by wvanbergen** [comment]
I guess the performance really depends on Kafka as well - which inside a VM is not very predictable. With KAFKA_PEERS we could point it to a real cluster for potentially more stable results?

**Comment by eapache** [comment]
I am still playing with that, slowly figuring out how to get reliable results. That's all cluster management though, this code can :ship:..

**Pull request merged**
