### PR TITLE
Workaround for missing offsets in Azure's OffsetFetchResponse

### PR DESCRIPTION
**Pull request by faec**
This is a fix for #1540. It adds an entry in the offset table for (consumer group, partition) pairs in the `OffsetFetchRequest` that are missing from the `OffsetFetchResponse`.

This is for discussion rather than immediate merge; in particular we aren't sure yet whether Azure plans to revert to their previous behavior (returning an explicit offset entry for new consumer groups), in which case this would be superfluous. However, this fix or something like it is a viable workaround in the event that this behavior persists.

### CODE REVIEW

**Comment by bai** [comment]
Thanks for your contribution. Could you please add a test for this?

**Comment by faec** [comment]
Test added! Sorry for the delay on the CLA -- this will be contributed on behalf of Elastic, we're just trying to figure out who to email to get me put on the official contributor list :-)

**Comment by o1egl** [comment]
@faec any updates about this PR?

**Comment by bai** [comment]
@o1egl according to https://github.com/Shopify/sarama/issues/1540#issuecomment-562259978 this PR shouldn't be relevant anymore. Are you still experiencing the issue?

**Comment by faec** [comment]
Yes, as far as I'm aware everything is working without the fix again... I've procrastinated on closing this in case the context was still relevant to someone but I think it's safe now, if this problem is still happening anywhere please follow up on #1540.

**Comment by o1egl** [comment]
@bai @faec I still get `kafka: response did not contain all the expected topic/partition blocks` error without this fix.

**Pull request closed without merging**
