### PR TITLE
Drop go 1.4 and update tools/docs appropriately

### PR DESCRIPTION
**Pull request by eapache**
@wvanbergen after fighting to get `go vet` working again on 1.4 I realized we were only about a week away from our 2 month guarantee. I'll merge this next week some time.

### CODE REVIEW

**Comment by wvanbergen** [comment]
:+1:

**Comment by wvanbergen** [comment]
🎉

**Comment by eapache** [comment]
Turns out @Sirupsen just released the new toxiproxy though which means merging this broke master because the API changed (at least I think that's the reason). It's a test-only breakage at least.

**Comment by Sirupsen** [comment]
@eapache Is this because you're using the Go API from master?

**Comment by eapache** [comment]
Ya I think so; we're installing 1.0.3 from tarball on CI, then using the master go API to talk to it. Is this as simple as switching to the 2.0 tarball?

**Comment by Sirupsen** [comment]
There may have been some minor changes to the Go client API, but I don't remember (Jake and Jacob did most of the work for 2.0)—it's probably about as simple as that, with maybe a couple of small exceptions.

**Pull request merged**
