### PR TITLE
Add describe log dirs request and response

### LINKED ISSUE #1313: get a partition log size
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.21.0
Kafka Version: 1.0.0
Go Version: 1.12

##### Problem Description

I would like to be able to get the Log Size for each partition in a specific topic/broker.
I even don't know if the Kafka API offer that info other than the JMX endpoint. 

I see a `AdminClient.describeLogDirs` API call on the  Java side at https://kafka.apache.org/21/javadoc/org/apache/kafka/clients/admin/DescribeLogDirsResult.html but not sure of what it contains.

```
Query the information of all log directories on the given set of brokers This is a convenience method for #describeLogDirs(Collection, DescribeLogDirsOptions) with default options. See the overload for more details. This operation is supported by brokers with version 1.0.0 or higher.
```

Any solution to get this information using Sarama ? 
Thanks

### PR DESCRIPTION
**Pull request by weeco**
Fixes #1313

### CODE REVIEW

**Comment by weeco** [comment]
I have signed the CLA and I believe the failed test was not caused by this PR.

**Comment by bai** [comment]
Many thanks for contributing. Do you think this one is ready for review? 👀

**Comment by weeco** [comment]
@bai Yes I think it is, I tested it against 2 different kafka clusters, but I'll further test it during the day. I'll contribute fixes today in case I find an issue with it.

Tomorrow I'll likely work on adding the DeleteRecords request/response

**Comment by weeco** [comment]
It is ready for review 👍

**Pull request merged**
