### PR TITLE
fix: zstd decoder does not appropriately closed.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
Our service use sarama as kafka produce, when we try to bump to v1.30.0, our CI found potential goroutine leak.

Please take the following as reference:
https://github.com/pingcap/ticdc/pull/3508
https://github.com/klauspost/compress/issues/451

### CODE REVIEW

**Comment by 3AceShowHand** [comment]
@dnwe 
@bai 

PTAL

**Comment by bai** [comment]
👋🏼 Thanks for your contribution! Could you please sign CLA?

**Comment by 3AceShowHand** [comment]
I should have already signed CLA, but it failed.

**Comment by 3AceShowHand** [comment]
so how about closing all decoders when closing the consumer ?

**Comment by dnwe** [comment]
But if a user has more than one consumer you can’t close the decoder until all of them have finished with it. So you’d have to refcount. 

A goroutine leak is when a blocked goroutine is left alive and can no longer be used or accessed. In this case the zstd decoder goroutines are intentionally kept around for re-use and don’t grow in number. Unless your app is never going to use Sarama again during its runtime there’s no real need to shutdown the decoder goroutines

**Pull request closed without merging**
