### PR TITLE
Fix hypothetical consumer deadlock, attempt 2

### PR DESCRIPTION
**Pull request by eapache**
Fixes bug #475 

Should be correct in all cases, unlike #483.

@Shopify/kafka

### CODE REVIEW

**Comment by eapache** [comment]
As I should have realized when the original ticket confused willem, the over-use of `dying` was the root problem. That value doesn't need synchronization, so just put it as a normal member.

**Comment by wvanbergen** [comment]
:shipit:

**Comment by horkhe** [comment]
@eapache @wvanbergen this change introduce a race over closing the `dying` channel. So PartitionConsumer.Close() may fail with panic: *close of closed channel*. And that is the reason why a build of #492 failed after rebase to master.

**Comment by eapache** [comment]
In my opinion that test is broken: it is user error to call `Close` or `AsyncClose` on a consumer after it has already closed, which it must have done because the `Messages` channel returned `!ok`.

**Comment by horkhe** [comment]
Consider this:
```
select {
case msg, ok := <-pc.Messages():
    if !ok {
        break // The consumer is closed
    }
    pc.Close() // Panic!!! because the channel was closed right after we checked the channel
```

**Comment by horkhe** [comment]
In other words since there is no atomic operation `checkChannelAndClose` the Close() operation is not reliable anymore.

**Pull request merged**
