### PR TITLE
Adds missing mock responses for mocking consumer group

### PR DESCRIPTION
**Pull request by krantideep95**

### CODE REVIEW

**Comment by seanschade** [comment]
@krantideep95 any chance you can add the CLA so this can be merged? I could really use the consumer group mocks as well. I am also using your `otel` library to instrument my consumers.

**Comment by krantideep95** [comment]
@seanschade I have signed the CLA. I think CLA check is failing for @carldunham whose branch I used for 1st commit.
Hey @carldunham do you mind signing the CLA? I created this Pull Request from your branch in #1631

**Comment by carldunham** [comment]
Sorry to be late here. Looks like you were able to bypass me, tho.

**Comment by d1egoaz** [comment]
@krantideep95 it looks like one of the files is no go formatted
image

**Comment by krantideep95** [comment]
@carldunham yeah, I squashed merged all your & my commits into 1 commit. 🙈 
@d1egoaz sorry about that. fixed that now.

**Review by d1egoaz — APPROVED** [review]

**Comment by d1egoaz** [comment]
Thanks @krantideep95

**Pull request merged**
