### PR TITLE
feat: protocol support for V11 fetch w/ rackID

### PR DESCRIPTION
**Pull request by dnwe**
These are the initial protocol beginnings to add support for follower
fetching (KIP-392). This commit simply adds configuration support for a
consumer to specify its rack identifier and to flow it in a V11
FetchRequest and correctly decode the "preferredReplica" field in the
response. Currently no further action is taken. A future PR will be
required to act upon this response.

### CODE REVIEW

**Comment by lizthegrey** [comment]
ooh, this is super exciting!

**Comment by bai** [comment]
👋 @dnwe you should have received an invite to join this repo as a collaborator so you could merge this PR and others that you see fit. Thank you so much for continued contributions.

**Comment by dnwe** [comment]
@bai thanks 😀 

As an aside, I have also been experimenting with generating the protocol Go code from the upstream .json-based format descriptions, which I thought might be interesting for Sarama v2.x — once I have something reasonable around that I'll push up a branch to collaborate over

**Comment by lizthegrey** [comment]
@dnwe when you do decide to work on the followup to read `PreferredReadReplica` values for fetch purposes, let me know and I'd be happy to collaborate or test, I just don't know this particular codebase well enough to wire together without help :)

**Comment by dneralla** [comment]
@lizthegrey @dnwe  I took a shot at that https://github.com/Shopify/sarama/pull/1696 
can you guys take a look ?

**Pull request merged**
