### PR TITLE
feat: expose IncrementalAlterConfigs API in admin.go

### PR DESCRIPTION
**Pull request by fengyinqiao**
For [#2083](https://github.com/Shopify/sarama/issues/2083)

### CODE REVIEW

**Comment by fengyinqiao** [comment]
@dnwe Could you please help to deal with this PR? @bai seems to be busy with something recently.

**Comment by dnwe** [comment]
Thanks @fengyinqiao — these changes look reasonable to me, a good extension to expose the functionality added under https://github.com/Shopify/sarama/pull/1966 — thanks for doing this PR

Please can you check on the CLA? Have you signed it with an email address that matches your GitHub username?

**Comment by fengyinqiao** [comment]
@dnwe I didn't expect you to reply so quickly. Thank you so much!!! And I have signed the CLA, but why is it still a problem?How can I re-run the CLA check?

**Comment by fengyinqiao** [comment]
@dnwe Sorry, that's my company email address for work. I didn't notice that... I can't use this email address to sign again, because my Github user name has already been signed, may I ask how to solve it?

**Comment by dnwe** [comment]
@fengyinqiao you can either add that email address as another contact address on this account, or you can “git commit —amend —reset-author” after changing your local git config to an email address that matches this GH account and then force push to your PR branch

**Comment by fengyinqiao** [comment]
> @dnwe Sorry, that's my company email address for work. I didn't notice that... I can't use this email address to sign again, because my Github user name has already been signed, may I ask how to solve it?
@dnwe  I have already added this email address to my GitHub account =_=, could you please run it again?

**Comment by dnwe** [comment]
Yep that’s passing now 🎉

**Comment by fengyinqiao** [comment]
@dnwe Once again, I would like to express my sincere thanks to you, for your so so so quick reply 🎉🎉🎉

**Comment by fengyinqiao** [comment]
@dnwe May I ask if this PR can be merged?

**Pull request merged**
