### PR TITLE
Remove cgo zstd package

### LINKED ISSUE #1252: Sending messages with ZStd compression enabled fails in multiple ways
##### Versions

Sarama Version: v1.20.1
Kafka Version: 2.1.0 (Scala version 2.12)
Go Version: 1.11.4

##### Configuration

What configuration values are you using for Sarama and Kafka?

Kafka configuration:
[server.properties.txt](https://github.com/Shopify/sarama/files/2750161/server.properties.txt)

##### Logs

```
=== RUN   TestSaramaZSTD
SARAMA: Initializing new client
SARAMA: client/metadata fetching metadata for all topics from broker localhost:9092
SARAMA: Connected to broker at localhost:9092 (unregistered)
SARAMA: client/brokers registered new broker #1 at localhost:9092
SARAMA: Successfully initialized new client
SARAMA: producer/broker/1 starting up
SARAMA: producer/broker/1 state change to [open] on sarama-test/0
SARAMA: Connected to broker at localhost:9092 (registered as #1)
SARAMA: client/metadata fetching metadata for [sarama-test] from broker localhost:9092
SARAMA: producer/broker/1 state change to [retrying] on sarama-test/0 because kafka server: Message contents does not match its CRC.
SARAMA: Retrying batch for sarama-test-0 because of kafka server: Message contents does not match its CRC.
TEST:   sending message failed: kafka server: Message contents does not match its CRC.
SARAMA: Producer shutting down.
SARAMA: Closing Client
SARAMA: producer/broker/1 shut down
SARAMA: Closed connection to broker localhost:9092
SARAMA: Initializing new client
SARAMA: client/metadata fetching metadata for all topics from broker localhost:9092
SARAMA: Closed connection to broker localhost:9092
SARAMA: Connected to broker at localhost:9092 (unregistered)
SARAMA: client/brokers registered new broker #1 at localhost:9092
SARAMA: Successfully initialized new client
SARAMA: producer/broker/1 starting up
SARAMA: producer/broker/1 state change to [open] on sarama-test/0
SARAMA: Connected to broker at localhost:9092 (registered as #1)
SARAMA: producer/broker/1 state change to [closing] because EOF
SARAMA: Closed connection to broker localhost:9092
TEST:   sending message failed: EOF
SARAMA: Producer shutting down.
SARAMA: Closing Client
SARAMA: Closed connection to broker localhost:9092
SARAMA: producer/broker/1 shut down
--- PASS: TestSaramaZSTD (0.01s)
PASS
ok  	gitlab.n0q.eu/go/engine/sarama-zstd	0.016s
```

##### Problem Description

I created a minimal test case to reproduce the issue:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"testing"

	"github.com/Shopify/sarama"
)

func TestSaramaZSTD(t *testing.T) {
	for _, kafkaVersion := range []sarama.KafkaVersion{sarama.V0_10_2_0, sarama.V2_1_0_0} {

		sarama.Logger = log.New(os.Stdout, "SARAMA: ", 0)

		cfg := sarama.NewConfig()

		cfg.ClientID = "sarama-zstd-test"

		cfg.Producer.Return.Errors = true
		cfg.Producer.Return.Successes = true
		cfg.Producer.Retry.Max = 0

		cfg.Version = kafkaVersion

		if err := cfg.Validate(); err != nil {
			t.Fatalf("configuration validation failed: %v", err)
		}

		cfg.Producer.Compression = sarama.CompressionZSTD

		producer, err := sarama.NewAsyncProducer([]string{"localhost:9092"}, cfg)
		if err != nil {
			t.Fatalf("sarama.NewAsyncProducer failed: %v", err)
		}

		producer.Input() <- &sarama.ProducerMessage{
			Topic: "sarama-test",
			Value: sarama.StringEncoder("hello world!"),
		}

		select {
		case <-producer.Successes():
			fmt.Println("TEST:   sending message was successful")
		case err := <-producer.Errors():
			fmt.Printf("TEST:   sending message failed: %v\n", err.Err)
		}

		if err := producer.Close(); err != nil {
			t.Errorf("producer.Close failed: %v", err)
		}
	}
}
```

The test program attempts to send a single message to Kafka using a `sarama.AsyncProducer` with ZStd compression enabled. It does so twice in a row, with different Kafka versions.

With version `sarama.V0_10_2_0`, it fails with the error output `TEST:   sending message failed: kafka server: Message contents does not match its CRC.`, whereas with version `sarama.V2_1_0_0`, it fails with the error message `TEST:   sending message failed: EOF`. In the latter case, Kafka also produces an error log output:

```
[2019-01-11 16:35:36,679] ERROR Closing socket for 127.0.0.1:9092-127.0.0.1:32884-1 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: PRODUCE, apiVersion: 3, connectionId: 127.0.0.1:9092-127.0.0.1:32884-1, listenerName: ListenerName(PLAINTEXT), principal: User:ANONYMOUS
Caused by: org.apache.kafka.common.record.InvalidRecordException: Produce requests with version 3 are note allowed to use ZStandard compression
[2019-01-11 16:35:36,684] ERROR Exception while processing request from 127.0.0.1:9092-127.0.0.1:32884-1 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: PRODUCE, apiVersion: 3, connectionId: 127.0.0.1:9092-127.0.0.1:32884-1, listenerName: ListenerName(PLAINTEXT), principal: User:ANONYMOUS
Caused by: org.apache.kafka.common.record.InvalidRecordException: Produce requests with version 3 are note allowed to use ZStandard compression
```

The expected behaviour for the first case is that sending the message works without causing an error.

The expected behaviour for the second case is that `cfg.Validate` indicates the invalid combination of Kafka version and compression codec.

### PR DESCRIPTION
**Pull request by klauspost**
Switch from cgo package to pure Go implementation. This will (when fixed) work even if no cgo is present.

https://github.com/klauspost/compress/tree/master/zstd#zstd

Compression level is removed. It could be made so the first request determines the compression level. But since there is currently only two levels (fast and default) I am not sure it is worth it.

This does NOT fix #1252 - only updates the code used for compression/decompression.

### CODE REVIEW

**Comment by klauspost** [comment]
CLA signed...

**Comment by bai** [comment]
Good timing, I just started to experiment with your lib yesterday to do exactly what this PR does. Thank you so much 👍

**Comment by d1egoaz** [comment]
this fixes:
- https://github.com/Shopify/sarama/issues/1197
- https://github.com/Shopify/sarama/issues/1215

**Comment by d1egoaz** [comment]
@bai might want to include your change to the build files, to disable explicitly cgo

**Comment by danielnelson** [comment]
We are running into issues with the new dependencies in https://github.com/influxdata/telegraf/issues/6344 and this would solve that issue.

I notice there is a relatively large init function though: https://github.com/klauspost/compress/blob/master/zstd/fse_predefined.go#L72

If this could be ran on first use or manually that would be ideal for us, since a very low number of Telegraf users would use this functionality but everyone would need to run the init code on startup.  I recognize this is mostly an issue with Telegraf but if these compression methods could be optional that would be very helpful for us.

**Comment by varun06** [comment]
```
--- FAIL: TestMessageEncoding (0.04s)
12041    request_test.go:34: Encoding empty zstd failed
12042        got  [53 28 155 77 1 4 0 0 1 88 141 205 89 56 255 255 255 255 255 255 255 255] 
12043        want [180 172 84 179 1 4 0 0 1 88 141 205 89 56 255 255 255 255 0 0 0 9 40 181 47 253 32 0 1 0 0]
```

looks like a valid failure.

**Comment by klauspost** [comment]
@varun06 Yeah, I guess it wants zero byte encoding to be have the complete wrapping. This just returns a 0 byte slice.

I will add an option to the encoder. Added PR: https://github.com/klauspost/compress/pull/155

@danielnelson Actually not an unreasonable thing 👍 I will take a look.

**Comment by bai** [comment]
Looks like the only thing that prevents this PR from being 🍏 is this newline that makes `go fmt` check fail: https://github.com/Shopify/sarama/commit/68a97de8c814474f902207cd6fe800fdb271c413. Proof on Travis: https://travis-ci.org/Shopify/sarama/builds/581646021.

Do you think you could remote that extra newline or cherry-pick my commit so we could get this merged? 🙏

**Comment by klauspost** [comment]
@bai Sorry. I had forgot to set up go fmt. Fixed now.

**Comment by bai** [comment]
Fantastic, thank you!

**Pull request merged**
