### PR TITLE
Shrink the scope of the partition circuit-breaker

### PR DESCRIPTION
**Pull request by eapache**
It shouldn't wrap the entirety of `assignPartition`, since that also protects
things like the call to actually choose the partition. The only thing it is
supposed to protect is the call to get the list of partitions, since that is
what can block.

This may or may not fix (or be the right way to fix) #466.

@ssahukar @Shopify/kafka

### CODE REVIEW

**Comment by wvanbergen** [comment]
I think this should fix #466.

How hard would it be to construct a test for this?

**Comment by eapache** [comment]
A test that partitioner errors are not part of the breaker, or a test that `Partition()` errors *are* part of the breaker? Neither is particularly tricky I don't think, but I'm also not sure if either are particularly useful.

**Comment by wvanbergen** [comment]
I think a test for a custom partitioner would be good. We explicitly designed to allow this but it's not really tested. The fact that it should be not part of the circuit breaker could be part of it.

A test for having `Partition()` inside a breaker would be nice to have to but is less needed IMHO.

**Comment by eapache** [comment]
test added; ended up touching a lot of lines because I generalized `expectSuccesses` to `expectResults`.

:eyes: when ready

**Comment by wvanbergen** [comment]
LGTM :+1:

**Pull request merged**
