### PR TITLE
fix(producer): return errors for every message in retryBatch to avoid producer hang forever

### PR DESCRIPTION
**Pull request by cch123**
This fixes https://github.com/Shopify/sarama/issues/2377

### CODE REVIEW

**Comment by cch123** [comment]
CLA signed

**Review by dnwe — APPROVED** [review]
Thanks for investigating this issue and submitting the fix, this change looks good to me

**Comment by dnwe** [comment]
@cch123 do you think you might be able to add a functional test that covers this scenario?

**Comment by cch123** [comment]
> @cch123 do you think you might be able to add a functional test that covers this scenario?

let me think about it.. I think the backoff param also didn't work, and need some time to find out why...

**Comment by cch123** [comment]
@dnwe PTAL

**Comment by dnwe** [comment]
Thanks!

**Pull request merged**
