### PR TITLE
add an interface to create client from broker list. 

### PR DESCRIPTION
**Pull request by hanbing0715**
add this interface to make create client for an group available

### CODE REVIEW

**Comment by hanbing0715** [comment]
maybe ci have something wrong,i can pass the "go fmt"but ci can't

**Comment by wvanbergen** [comment]
CI, including `make fmt` was working fine yesterday. I also rebuilt master just now (https://travis-ci.org/Shopify/sarama/builds/218407653), and it is working fine. So it must be something with your branch.

**Comment by wvanbergen** [comment]
What is the use case you have for this function? You can already create a client with the broker address as strings, which is pretty easy to obtain from a list of Broker objects (which you normally only have access to once you already have a client anyway)

**Comment by hanbing0715** [comment]
i have make a commit to pass the ci
https://travis-ci.org/hanbing0715/sarama
and i will add my use case later

**Comment by hanbing0715** [comment]
close the pr for a bug

**Pull request closed without merging**
