### PR TITLE
Support Create Topics

### PR DESCRIPTION
**Pull request by cmshetty**
We use this change to create Kafka topics in our deployment process.

### CODE REVIEW

**Comment by chandradeepak** [comment]
Does this create topics work only with kafka 0.11 or older versions as well ? Is this the new admin API that is done [admin api](https://cwiki.apache.org/confluence/display/KAFKA/KIP-117%3A+Add+a+public+AdminClient+API+for+Kafka+admin+operations) ? 

Please confirm. previously create topics is done to zoo keeper directly. Now can that be done with kafka directly using sarama ?

**Comment by cmshetty** [comment]
This uses the create topics request introduced in 0.10.1.0. See https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations.

**Comment by fgeller** [comment]
Is this PR out of scope for sarama or is there something I could help with here?

**Comment by cmshetty** [comment]
Hi @fgeller I added this PR when I was working with Kafka. I have been on a new project the past 4 months. It would be great if this could be merged into Sarama.

I think it needs more tests and testing. We had not tested it across various versions and scenarios.

I don't think it is out of scope but I haven't been following Sarama since June.

**Comment by eapache** [comment]
Ya, sorry I never got around to looking at this properly. I'd be happy to accept something along these lines into Sarama, with a few comments on the specific code here:
- I'd prefer splitting it up into two PRs, one that adds support for the new Metadata/Broker versions, and one that actually adds CreateTopic support; it will be easier to deal with that way
- As Chandra mentioned it needs more tests

**Comment by fgeller** [comment]
cool - thank @eapache !
@cmshetty would you mind me picking this up or do you want to continue working on this?

**Comment by cmshetty** [comment]
@fgeller please go ahead. I don't have the time right now to work on this. Thank you for taking this up.

**Comment by willastronomer** [comment]
This would be really useful. Do you need a hand with anything @fgeller?

**Comment by toddpalino** [comment]
+1 on this. Any updates?

**Comment by toddpalino** [comment]
@fellyns, we should keep an eye on this one. Support for CreateTopic will be required shortly for any sort of programmatic topic creation. It's probably not a big deal yet, but could become one.

**Comment by zhongyi-zhang** [comment]
+1 on this. It is really useful.

**Comment by fellyns** [comment]
Thanks for highlighting this Todd! Looking forward to this feature as it looks like we'll be needing this internally at LinkedIn soon. @fgeller If there is anything I can do to help this effort along let me know.

**Comment by varun06** [comment]
This will be helpful, any update, also let me know if any help is needed?

**Comment by buyology** [comment]
anyone actively working on this?

**Comment by eapache** [comment]
I think it's pretty dead at this point. I'm still happy to accept a cleaned up version of this feature as described in https://github.com/Shopify/sarama/pull/852#issuecomment-328091942 though.

**Pull request closed without merging**
