### PR TITLE
Permit setting version on mock fetch response

### PR DESCRIPTION
**Pull request by eapache**
@sanchezl this should address #938.

### CODE REVIEW

**Comment by sanchezl** [comment]
Thanks @eapache. Would you consider an additional API such as:
```go
func (mfr *MockFetchResponse) SetMaxVersion(kafkaVersion KafkaVersion) *MockFetchResponse {
switch {
  case kafkaVersion.IsAtLeast(sarama.V0_11_0_0): // e.g. when supported
    mfr.version = 3
  case kafkaVersion.IsAtLeast(sarama.V0_10_0_0):
    mfr.version = 2
  default:
    mfr.version = 1
}
return mfr
}
```

**Comment by eapache** [comment]
Hmm, actually would it just be simpler to return the same version of FetchResponse as was received in the FetchRequest? That would be simpler, but I'm not sure if they line up in all cases?

**Comment by sanchezl** [comment]
What about just adding property to the MockBroker itself (e.g. `MockBroker.setMessageFormat(kafkaVersion KafkaVersion)` that would correspond to setting the `log.message.format.version` property on a real kafka server.

I advocate for the use of `KafkaVersion`, not just the message version since that is what the `log.message.format.version` property expects.

**Comment by eapache** [comment]
> I advocate for the use of KafkaVersion, not just the message version since that is what the log.message.format.version property expects.

AFAICT log.message.format.version refers to the version of the actual `Message` data struct, not the Request/Response wire protocol. They are versioned differently.

**Comment by eapache** [comment]
I've reviewed this some more and I think the PR I have here is correct. The wire protocol version should be flexible even knowing the broker version.

**Pull request merged**
